/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestaodetarefas.view;

import gestaodetarefas.controller.CategoriaController;
import gestaodetarefas.model.entities.Categoria;
import gestaodetarefas.model.entities.Usuario;
import java.awt.Component;
import java.util.List;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author Ceres
 */
public class MainView extends javax.swing.JFrame {

    private Usuario usuario;

    /**
     * Creates new form MainFrame
     */
    public MainView(Usuario usuario) {
        this.usuario = usuario;
        initComponents();

        lb.setText(lb.getText() + usuario.getNome());

        // Carregando categorias
        lista.setModel(new DefaultTreeModel(new DefaultMutableTreeNode()));
        lista.setCellRenderer(new CategoriasTreeCellRenderer());
        lista.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        lista.setRootVisible(true);
        lista_carregarCategorias();
    }

    public void lista_carregarCategorias() {

        CategoriaController controller = new CategoriaController();
        List<Categoria> categorias = controller.select(usuario.getId());

        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Categorias");
        for (int i = 0; i < categorias.size(); i++) {

            DefaultMutableTreeNode temp = new DefaultMutableTreeNode(categorias.get(i));
            root.add(temp);
        }

        lista.setModel(new DefaultTreeModel(root));
        lista.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. <br>
     * The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lb = new javax.swing.JLabel();
        splitRedimencionar = new javax.swing.JSplitPane();
        scrollLista = new javax.swing.JScrollPane();
        lista = new javax.swing.JTree();
        pnPainel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb.setText("Tarefas : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(lb, gridBagConstraints);

        scrollLista.setMinimumSize(new java.awt.Dimension(100, 16));
        scrollLista.setPreferredSize(new java.awt.Dimension(100, 362));

        lista.setMaximumSize(new java.awt.Dimension(100, 74));
        lista.setMinimumSize(new java.awt.Dimension(100, 0));
        lista.setPreferredSize(new java.awt.Dimension(100, 74));
        scrollLista.setViewportView(lista);

        splitRedimencionar.setLeftComponent(scrollLista);

        javax.swing.GroupLayout pnPainelLayout = new javax.swing.GroupLayout(pnPainel);
        pnPainel.setLayout(pnPainelLayout);
        pnPainelLayout.setHorizontalGroup(
            pnPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );
        pnPainelLayout.setVerticalGroup(
            pnPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        splitRedimencionar.setRightComponent(pnPainel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(splitRedimencionar, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb;
    private javax.swing.JTree lista;
    private javax.swing.JPanel pnPainel;
    private javax.swing.JScrollPane scrollLista;
    private javax.swing.JSplitPane splitRedimencionar;
    // End of variables declaration//GEN-END:variables

    private class CategoriasTreeCellRenderer extends DefaultTreeCellRenderer {

        public CategoriasTreeCellRenderer() {
        }

        public Component getTreeCellRendererComponent(JTree tree, Object value, boolean sel, boolean expanded, boolean leaf, int row, boolean thasFocus) {

            super.getTreeCellRendererComponent(tree, value, sel, expanded, leaf, row, hasFocus);
            DefaultMutableTreeNode no = (DefaultMutableTreeNode) value;

            if (no.getUserObject() == null) {
                return this;

            } else if (Categoria.class.isInstance(no.getUserObject())) {
                Categoria x = (Categoria) no.getUserObject();
                this.setText(x.getNome());
            }

            return this;
        }
    }

}
